/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    EmptyLayout: typeof import('./src/layouts/EmptyLayout.vue')['default']
    MainLayout: typeof import('./src/layouts/default/MainLayout.vue')['default']
    Mbtn: typeof import('./src/components/Mbtn.vue')['default']
    MBtn: typeof import('./src/components/M-btn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestingView: typeof import('./src/components/TestingView.vue')['default']
    UserLayout: typeof import('./src/layouts/UserLayout.vue')['default']
  }
}
