name: README Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 8 * * 0" # Every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup Nodejs 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Cache dependencies and build outputs to improve workflow speed
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install
      - name: Generate README 
        run: npm run prep
      - name: GIT Commit
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "flamur.biz@hotmail.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
      # - name: Stage changes
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       git add README.md
      # - name: Commit changes
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       git commit -m "Update README"
      # - name: Push changes
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       git push
        