name: README Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *" # Every Hour

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Updated README
      CI_COMMIT_AUTHOR: Flamur

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup Nodejs 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Cache dependencies and build outputs to improve workflow speed
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install
      - name: Generate README 
        run: npm run prep
      - name: GIT Commit and Push changes
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "flamur.biz@hotmail.com"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          else
            echo "No changes to commit"
          fi
        # run: |
        #   git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        #   git config --global user.email "flamur.biz@hotmail.com"
        #   git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        #   git push
        # git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        # git push