name: README Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 8 * * 0" # Every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup Nodejs 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Cache dependencies and build outputs to improve workflow speed
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Configure Git
        uses: actions/github-script@v6
        with:
          script: |
            git config user.name "Flamur Fazliu"
            git config user.email "flamur.biz@hotmail.com"
      - name: Generate README 
        run: npm run prep
      - name: Stage changes
        uses: actions/github-script@v4
        with:
          script: |
            git add README.md
      - name: Commit changes
        uses: actions/github-script@v4
        with:
          script: |
            git commit -m "Update README"
      - name: Push changes
        uses: actions/github-script@v4
        with:
          script: |
            git push
      - name: Commit and Push new README.md to the repo
        uses: mikeal/publish-to-github-action@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        